esphome:
  name: rfid
  friendly_name: RFID

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rfid Fallback Hotspot"
    password: "XXXXXXXXXXXX"

captive_portal:
    
spi:
  clk_pin: GPIO0
  mosi_pin: GPIO4
  miso_pin: GPIO5
  id: "rfid"

rc522_spi:
  cs_pin: GPIO2
  reset_pin: GPIO14
  spi_id: "rfid"

binary_sensor:
  - platform: rc522
    uid: X1-11-11-11
    name: "Porte_clef"
  - platform: rc522
    uid: X1-11-11-11
    name: "carte"
  - platform: rc522
    uid: X1-11-11-11
    name: "carte tan"
  - platform: rc522
    uid: x1-11-11-11
    name: "carte bleu"

